# Generated by Django 5.2.11 on 2026-06-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_merge_0017_merge_20260617_0000_0018_report_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='demosubmission',
            name='advance_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='demosubmission',
            name='full_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='demosubmission',
            name='lead_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demosubmission',
            name='manager_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demosubmission',
            name='status',
            field=models.CharField(choices=[('pending_lead', 'Pending Lead Review'), ('lead_rejected', 'Rejected by Team Lead'), ('pending_manager', 'Pending PM Review'), ('manager_rejected', 'Rejected by PM'), ('manager_accepted', 'Accepted by PM'), ('client_approved', 'Approved by Client'), ('rejected', 'Rejected')], default='pending_lead', max_length=30),
        ),
    ]
