# Generated by Django 6.0.5 on 2026-06-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_demosubmission_advance_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
